# Site settings
title: Of sketching and cakes
email: elena.sanna.mvk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Elenamvk's portfolio/website - jr web dev wit a passion for food, code and ux.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: elenamvk
# github_username:  elenamvk

# Build settings
markdown: kramdown
exclude: ['README.md', 'GEMFILE', 'GEMFILE.lock']


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: bfd952
  secondary: 9cb82f  
  secondary-dark: 333

# Team names, titles and social links
people:

- name: Elena Mvk
  pic: 1
  position: I moved to England during my gap year to play some serious rugby and after perfecting my flat white skills I decided to pursue a different challenge. I always had an interest for coding - so I decided to enrol in the General Assembly Web Development Immersive bootcamp to complete my previous experiences in Information Architecture and UX. I have now a fair amount of google-fu under my belt; various web app already deployed and a much better understanding of the distance existing between good user experience and good code. I'm currently working as a jr web developer for Positive Luxury and studying everyday; but I also cultivate personal coding/illustration/graphic design projects in my spare time and play a lot of rugby on Sundays!
  social:
    - title: twitter
      url: http://twitter.com/elenamvk
    - title: behance
      url: http://behance.com/elenamvk
    - title: github
      url: http://github.com/elenamvk
    - title: linkedin
      url: https://www.linkedin.com/in/elenasanna

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/elenamvk
  - title: behance
    url: http://behance.com/elenamvk
  - title: github
    url: http://github.com/elenamvk
  - title: linkedin
    url: https://www.linkedin.com/in/elenasanna

