# Site settings
title: Big about cakes and code
email: elena.sanna.mvk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: elenamvk
github_username:  elenamvk

# Build settings
markdown: kramdown
exclude: ['README.md', 'GEMFILE', 'GEMFILE.lock']
