# Site settings
title: Big about cakes and code
email: elena.sanna.mvk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: elenamvk
# github_username:  elenamvk

# Build settings
markdown: kramdown
exclude: ['README.md', 'GEMFILE', 'GEMFILE.lock']


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:

- name: Elena Mvk
  pic: 2
  position: UXer and Web Devver
  social:
    - title: twitter
      url: http://twitter.com/elenamvk
    - title: behance
      url: http://behance.com/elenamvk
    - title: github
      url: http://github.com/elenamvk
    - title: linkedin
      url: https://www.linkedin.com/in/elenasanna

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/elenamvk
  - title: Behance
    url: http://behance.com/elenamvk
  - title: github
    url: http://github.com/elenamvk

