# Site settings
title: Of sketching and cakes
email: elena.sanna.mvk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: elenamvk
# github_username:  elenamvk

# Build settings
markdown: kramdown
exclude: ['README.md', 'GEMFILE', 'GEMFILE.lock']


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:

- name: Elena Mvk
  pic: 1
  position: I moved to England during my gap year and after seven month of learning to perfect the perfect flat white I decided I needed to pursue a different challenge. I always had an interest for development - so decided to enrol in the General Assembly Web Development Immersive course to complete my previous experience in Information Architecture and User Experience. I now find myself a budding developer with a fair amount of google-fu knowledge under my belt; two web app already deployed and a much better understanding of how much distance a good User Experience-er needs to bridge the gap between user needs and coding abilities. This being said my learning curve is just at the beginning and I hope to further my self-education under Agile wings and senior colleagues.
  social:
    - title: twitter
      url: http://twitter.com/elenamvk
    - title: behance
      url: http://behance.com/elenamvk
    - title: github
      url: http://github.com/elenamvk
    - title: linkedin
      url: https://www.linkedin.com/in/elenasanna

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/elenamvk
  - title: behance
    url: http://behance.com/elenamvk
  - title: github
    url: http://github.com/elenamvk
  - title: linkedin
    url: https://www.linkedin.com/in/elenasanna

